services:
  ros2-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: nrgchandra/ros2-core:latest
    container_name: seva_ros2_core
    network_mode: "host"
    environment:
      ROS_DOMAIN_ID: "0"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      MQTT_HOST: "127.0.0.1"
      MQTT_PORT: "1883"
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: "6379"
    restart: unless-stopped
