<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>seva_bringup</name>
  <version>0.1.0</version>
  <description>Launch configurations for Seva Sarathi MEC system</description>
  <maintainer email="nrgchandra@gmail.com">Anurag Chandra</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>seva_telemetry</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
